name: Pages

on:
  push:
    branches:
      - src # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc
      - name: Install Dependencies
        run: npm install
      - name: Build Astro
        run: |
          cd astro
          npm install pnpm -g
          pnpm install
          pnpm build
          cd ..
          node build_fin.js
      - name: Build Hexo
        run: npm run build
      - name: Recopy Astro # Hexo 会删 index.html
        run: node build_fin.js
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
